const $=id=>document.getElementById(id);
let state=null,token='',flipped=false,review=null,boardKey='',lastFen='',nodes=new Map(),oldPieces={},oldPly=0,noticeDismissed='',health=null,toastTimer;
const startFen='rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1';
const names={p:'pawn',n:'knight',b:'bishop',r:'rook',q:'queen',k:'king'};
function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
async function api(path,data){const r=await fetch(path,data===undefined?{}:{method:'POST',headers:{'Content-Type':'application/json','X-Arena-Token':token},body:JSON.stringify(data)});const j=await r.json();if(!r.ok)throw Error(j.error||'Request failed');return j}
function toast(s){$('toast').textContent=s;$('toast').classList.remove('hidden');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.add('hidden'),3500)}
async function healthCheck(){try{const h=await api('/api/health');token=h.token;health=h.providers;$('connection').textContent='Local server online';$('connectionLight').style.background='';$('readiness').textContent=(health.jev?'Jev connected':'Jev key needed')+' · '+(health.laya?'Laya ready':'Laya offline')}catch(e){$('connection').textContent='Server offline';$('connectionLight').style.background='#d77f69';$('readiness').textContent='Start-Local.ps1 starts both services'}}
function fenPieces(fen){const pieces={};fen.split(' ')[0].split('/').forEach((row,ri)=>{let file=0;for(const c of row){if(/\d/.test(c))file+=+c;else{pieces[String.fromCharCode(97+file)+(8-ri)]=c;file++}}});return pieces}
function position(square){let x=square.charCodeAt(0)-97,y=8-Number(square[1]);if(flipped){x=7-x;y=7-y}return[x,y]}
function drawSquares(){const box=$('squares');box.innerHTML='';for(let r=0;r<8;r++)for(let f=0;f<8;f++){const file=flipped?7-f:f,rank=flipped?r+1:8-r,square=String.fromCharCode(97+file)+rank;const cell=document.createElement('div');cell.className='square'+((r+f)%2?' dark':'');cell.dataset.square=square;cell.setAttribute('role','gridcell');cell.setAttribute('aria-label',square);if(f===0)cell.innerHTML+=`<span class="coordinate rank">${rank}</span>`;if(r===7)cell.innerHTML+=`<span class="coordinate file">${String.fromCharCode(97+file)}</span>`;box.append(cell)}}
function moveNode(from,to){const node=nodes.get(from);if(!node)return;const target=nodes.get(to);if(target&&target!==node)target.remove();nodes.delete(from);nodes.set(to,node);node.classList.add('moving');setTimeout(()=>node.classList.remove('moving'),400)}
function drawBoard(){if(!state)return;const history=state.history,ply=review===null?history.length:Math.min(review,history.length),fen=ply?history[ply-1].fen:startFen,pcs=fenPieces(fen),key=state.run_id+':'+state.game;const last=ply?history[ply-1]:null;
if(key!==boardKey){nodes.forEach(n=>n.remove());nodes.clear();oldPieces={};oldPly=0;boardKey=key;lastFen=''}
if(fen!==lastFen&&ply===oldPly+1&&last){moveNode(last.uci.slice(0,2),last.uci.slice(2,4));const from=last.uci.slice(0,2),to=last.uci.slice(2,4);if(oldPieces[from]?.toLowerCase()==='k'&&Math.abs(from.charCodeAt(0)-to.charCodeAt(0))===2){const rank=from[1];moveNode(to[0]==='g'?'h'+rank:'a'+rank,to[0]==='g'?'f'+rank:'d'+rank)}}
for(const [sq,n] of [...nodes])if(!pcs[sq]){n.remove();nodes.delete(sq)}
for(const [sq,p] of Object.entries(pcs)){let n=nodes.get(sq);if(!n){n=document.createElement('div');n.className='piece';n.innerHTML='<img draggable="false">';$('pieces').append(n);nodes.set(sq,n)}const img=n.firstChild;const url='/pieces/'+p+'.svg';if(img.getAttribute('src')!==url)img.src=url;img.alt=(p===p.toUpperCase()?'White ':'Black ')+names[p.toLowerCase()]+' on '+sq;const[x,y]=position(sq);n.style.transform=`translate(${x*100}%,${y*100}%)`}
for(const cell of $('squares').children){const sq=cell.dataset.square;cell.classList.toggle('last',!!last&&(sq===last.uci.slice(0,2)||sq===last.uci.slice(2,4)));cell.classList.toggle('check',review===null&&sq===state.check_square);cell.setAttribute('aria-label',sq+(pcs[sq]?' '+(pcs[sq]===pcs[sq].toUpperCase()?'white ':'black ')+names[pcs[sq].toLowerCase()]:' empty'))}
lastFen=fen;oldPieces=pcs;oldPly=ply;$('positionStatus').innerHTML='<i></i>'+esc(review!==null?`Reviewing ply ${ply} of ${history.length}`:state.check?'Check · '+state.turn+' to move':history.length?state.turn[0].toUpperCase()+state.turn.slice(1)+' to move':'Starting position');$('live').style.color=review===null?'var(--green)':'';$('first').disabled=ply===0;$('prev').disabled=ply===0;$('next').disabled=ply===history.length;
}
function player(prefix,side){const name=state.policies[side],stat=state.stats[side],active=state.thinking===name&&state.status==='running';$(prefix+'Avatar').textContent=name==='jev'?'J':'L';$(prefix+'Avatar').className='avatar '+(name==='jev'?'orange':'mint');$(prefix+'Name').innerHTML=esc(name[0].toUpperCase()+name.slice(1))+` <span>${side===0?'WHITE':'BLACK'}</span>`;$(prefix+'Source').textContent=name==='jev'?'TypeSafe · via '+(health?.jev_provider==='openrouter'?'OpenRouter':'direct API'):'Local GPU · open weights';$(prefix+'Player').classList.toggle('thinking',active);const clock=$(prefix+'Clock');clock.querySelector('span').textContent=active?'THINKING':state.status==='paused'?'PAUSED':'LAST DECISION';clock.querySelector('b').textContent=active?((Date.now()/1000-state.thinking_since).toFixed(1)+'s'):stat.last_ms===null?'—':(stat.last_ms/1000).toFixed(2)+'s';
const captured=state.history.slice(0,review??state.history.length).filter(m=>m.side===side&&m.captured).map(m=>m.captured);$(prefix+'Captured').innerHTML=captured.map(p=>`<img alt="Captured ${names[p.toLowerCase()]}" src="/pieces/${p}.svg">`).join('')}
let moveListKey='';function renderMoves(){const key=state.run_id+':'+state.game+':'+state.history.length+':'+review;if(key===moveListKey)return;moveListKey=key;if(!state.history.length){$('moveList').innerHTML='<div class="empty"><span>♙</span><strong>No moves yet.</strong><p>Start a match to watch Jev and Laya play.</p></div>';return}let html='';for(let i=0;i<state.history.length;i+=2){html+=`<div class="move-row"><span>${i/2+1}.</span>`;for(let j=i;j<i+2;j++){const m=state.history[j];html+=m?`<button data-ply="${j+1}" class="${(review===null?state.history.length:review)===j+1?'active':''}" title="${esc(m.source)} · ${m.latency_ms} ms">${esc(m.san)}</button>`:'<span></span>'}html+='</div>'}$('moveList').innerHTML=html;if(review===null)$('moveList').scrollTop=$('moveList').scrollHeight}
function renderDetails(){const row=review===null?state.history.at(-1):state.history[review-1];if(!row){$('choiceName').textContent='Waiting for a decision';$('choiceNote').textContent='Shared analysis prepares candidates; Jev or Laya chooses the move.';$('probabilities').innerHTML='';$('analysisNotes').innerHTML='';return}$('choiceName').textContent=row.source[0].toUpperCase()+row.source.slice(1)+' · '+row.san;$('choiceNote').textContent=`${(row.latency_ms/1000).toFixed(2)}s · ${row.model}`;const a=row.assistance;$('analysisNotes').innerHTML=a?'<p><b>'+esc(a.engine)+' · '+esc(a.analyst)+'</b></p>'+a.candidates.map(c=>'<p class="candidate"><b>'+esc(c.san)+' · '+esc(c.category||'candidate')+'</b><br>'+esc(c.note)+'<br><small>Immediate reply: '+esc(c.reply||'none')+(c.repeat?' · repeats':'')+'</small></p>').join('')+(a.warning?'<p>'+esc(a.warning)+'</p>':''):'<p>Unassisted baseline: no search or analyst.</p>';const stage=row.stages.at(-1);$('probabilities').innerHTML=Object.entries(stage.probabilities).sort((a,b)=>b[1]-a[1]).slice(0,7).map(([key,p])=>`<div class="prob"><span>${esc(stage.labels[key]?.split(':')[0]?.split(' (')[0]||key)}</span><div class="prob-track"><i style="width:${p*100}%"></i></div><small>${Math.round(p*100)}%</small></div>`).join('')}
function render(){if(!state)return;$('assistanceBanner').textContent=state.mode==='assisted'?'LIGHTWEIGHT · Same two-ply analysis → Jev / Laya · Stockfish reviews afterward':'UNASSISTED · Original baseline · No search or analyst';const active=['running','paused','stopping','reviewing'].includes(state.status);$('start').disabled=active;$('pause').disabled=!['running','paused'].includes(state.status);$('pause').textContent=state.status==='paused'?'▶ Resume':'Ⅱ Pause';$('stop').disabled=!active||state.status==='stopping';for(const id of ['whitePolicy','games','delay','mode'])$(id).disabled=active;$('status').textContent=state.status.toUpperCase();$('status').className='status '+state.status;$('phase').textContent=state.phase;$('phaseDot').parentElement.classList.toggle('busy',state.status==='running');$('error').textContent=state.error||'';$('error').classList.toggle('hidden',!state.error);$('moveCount').textContent=state.history.length;$('legalCount').textContent=state.legal_moves.length;$('calls').textContent=state.calls;$('budgetLabel').textContent=state.budget.toLocaleString()+'-request match cap';$('gameCount').textContent='GAME '+String(state.game).padStart(2,'0')+' / '+String(state.games).padStart(2,'0');let scores={jev:0,laya:0};for(const r of state.results){if(r.result==='1/2-1/2'){scores.jev+=.5;scores.laya+=.5}else if(r.result==='1-0')scores[r.policies[0]]++;else if(r.result==='0-1')scores[r.policies[1]]++}$('jevScore').textContent=scores.jev;$('layaScore').textContent=scores.laya;player('white',flipped?1:0);player('black',flipped?0:1);drawBoard();renderMoves();renderDetails();renderReview();const noticeKey=state.run_id+':'+state.game+':'+state.result;const finished=state.result!=='*';$('boardNotice').classList.toggle('hidden',!finished||noticeDismissed===noticeKey||review!==null);if(finished){$('noticeTitle').textContent=state.result==='1/2-1/2'?'A drawn game.':(state.result==='1-0'?state.policies[0]:state.policies[1]).replace(/^./,c=>c.toUpperCase())+' wins.';$('noticeText').textContent=state.termination+' · '+state.result}}
async function command(path,data={}){try{await api(path,data);await poll()}catch(e){toast(e.message)}}
$('start').onclick=()=>{review=null;noticeDismissed='';const white=$('whitePolicy').value;command('/api/start',{mode:$('mode').value,policies:[white,white==='jev'?'laya':'jev'],games:Number($('games').value),delay:Number($('delay').value),budget:1000,max_plies:400})};$('pause').onclick=()=>command('/api/pause');$('stop').onclick=()=>command('/api/stop');$('refresh').onclick=healthCheck;
function flip(){flipped=!flipped;drawSquares();render()}$('flip').onclick=flip;$('flipRail').onclick=flip;
function seek(p){if(!state)return;review=p===null?null:Math.max(0,Math.min(p,state.history.length));render()}$('first').onclick=()=>seek(0);$('prev').onclick=()=>seek((review??state.history.length)-1);$('next').onclick=()=>seek((review??state.history.length)+1);$('live').onclick=()=>seek(null);$('moveList').onclick=e=>{const b=e.target.closest('[data-ply]');if(b)seek(Number(b.dataset.ply))};$('dismissNotice').onclick=()=>{noticeDismissed=state.run_id+':'+state.game+':'+state.result;render()};
function tab(details){$('detailsPanel').classList.toggle('hidden',!details);$('movesPanel').classList.toggle('hidden',details);$('movesTab').classList.toggle('selected',!details);$('detailsTab').classList.toggle('selected',details)}$('movesTab').onclick=()=>tab(false);$('detailsTab').onclick=()=>tab(true);
function download(){if(!state)return;const blob=new Blob([state.pgn],{type:'application/x-chess-pgn'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=(state.run_id||'jev-laya')+'-game-'+state.game+'.pgn';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}$('download').onclick=download;$('downloadRail').onclick=download;
let polling=false;async function poll(){if(polling)return;polling=true;try{const next=await api('/api/state');if(state&&(next.run_id!==state.run_id||next.game!==state.game))review=null;state=next;render()}catch(e){$('connection').textContent='Reconnecting…'}finally{polling=false}}
drawSquares();healthCheck();poll();setInterval(poll,300);setInterval(()=>{if(state?.thinking&&state.status==='running'){player('white',flipped?1:0);player('black',flipped?0:1)}},100);


function renderReview(){
 const r=state.review,p=state.review_progress;
 $('reviewStatus').textContent=state.status==='reviewing'?`Stockfish reviewing: ${p?.done||0} / ${p?.total||0} half-moves`:r?.status==='complete'?`${r.engine} · review complete`:r?.status==='error'?`Review unavailable: ${r.error}`:'Stockfish starts after the game ends. It never supplies live moves.';
 if(r?.status!=='complete'){$('reviewScores').innerHTML='';$('reviewMethod').textContent='';$('reviewMoves').innerHTML='';return}
 $('reviewScores').innerHTML=r.players.map(p=>`<article><span>${esc(p.model.toUpperCase())} · ${esc(p.color)}</span><h3>${p.average_cp_loss??'—'}<small>average cp loss</small></h3><div class="review-counts"><span>${p.counts.blunder} blunders</span><span>${p.counts.mistake} mistakes</span><span>${p.counts.inaccuracy} inaccuracies</span></div><p>${p.best_move_matches}/${p.moves} engine first-choice matches · ${p.missed_forced_mates} missed forced mates · ${p.allowed_forced_mates} allowed forced mates</p><small>Elo rating: not established from one match</small></article>`).join('');
 $('reviewMethod').textContent=r.method+' '+r.search+' '+r.limitations;
 $('reviewMoves').innerHTML='<div class="review-table-head">MOVE · MODEL / PLAYED / ENGINE ALTERNATIVE / LOSS</div>'+r.moves.filter(m=>m.loss_cp>50||m.missed_mate||m.allowed_mate).map(m=>`<button data-ply="${m.ply}"><span>${Math.ceil(m.ply/2)}${m.side?'…':'.'} ${esc(state.policies[m.side])}</span><b>${esc(m.san)}</b><span>Best: ${esc(m.best_san)}</span><span>${m.loss_cp} cp · ${m.allowed_mate?'allows forced mate':m.missed_mate?'misses forced mate':esc(m.classification)}</span></button>`).join('');
}
$('reviewMoves').onclick=e=>{const b=e.target.closest('[data-ply]');if(b)seek(Number(b.dataset.ply))};
